node_modules
.git
.github
!.github
!.github/scripts
!.github/scripts/enforce-package-manager.js
!.github/hooks
.nx
.nxcache
.vscode
.editorconfig

**/*.log
coverage
test-results
tsconfig.tsbuildinfo

e2e
!e2e/package.json
docker

# Ignore existing built admin (will rebuild inside container)
ghost/core/core/built/admin
