node_modules
.git
.github
.nx
.nxcache
.vscode
.editorconfig

**/*.log
coverage
test-results
tsconfig.tsbuildinfo

e2e
!e2e/package.json
docker

# Ignore existing built admin (will rebuild inside container)
ghost/core/core/built/admin
